function data()
    return {
        en = {
            ["mod_description"] = "Automatically names new lines based on customizable naming conventions",

            -- Settings Window
            ["gui_settings_title"] = "Auto Line Namer Settings",
            ["gui_settings_tooltip"] = "Open Auto Line Namer Settings",
            ["gui_settings_button_label"] = "[ALN]",
            -- General Tab
            ["gui_settings_tab_general"] = "General",
            ["gui_settings_tab_general_enabling_title"] = "Enabling:",
            ["gui_settings_tab_general_enabling_description"] = "Enable or disable the mod",
            ["gui_settings_tab_general_enabling_tooltip"] = "Enable or disable the mod",
            ["gui_settings_tab_general_prefix_title"] = "Disable Prefix:",
            ["gui_settings_tab_general_prefix_description"] = "Disable Prefix",
            ["gui_settings_tab_general_prefix_tooltip"] = "Lines that have this prefix will not be renamed",
            ["gui_settings_tab_general_convention_title"] = "Active Convention:",
            ["gui_settings_tab_general_convention_description"] = "Active Convention",
            ["gui_settings_tab_general_convention_tooltip"] = "Select the active naming convention",
            ["gui_settings_tab_general_autoUpdate_title"] = "Auto Update:",
            ["gui_settings_tab_general_autoUpdate_description"] = "Auto Update",
            ["gui_settings_tab_general_autoUpdate_tooltip"] = "Automatically update the line names",
            ["gui_settings_tab_general_autoUpdateInterval_title"] = "Auto Update Interval",
            ["gui_settings_tab_general_autoUpdateInterval_description"] = "minutes",
            ["gui_settings_tab_general_autoUpdateInterval_tooltip"] = "Set the interval for the auto update",
            -- Transport Types Tab
            ["gui_settings_tab_transportType"] = "Transport Types",
            ["gui_settings_tab_transportType_roadPassenger_title"] = "Road Passenger:",
            ["gui_settings_tab_transportType_roadPassenger_description"] = "Road Passenger",
            ["gui_settings_tab_transportType_tramPassenger_title"] = "Tram Passenger:",
            ["gui_settings_tab_transportType_tramPassenger_description"] = "Tram Passenger",
            ["gui_settings_tab_transportType_trainPassenger_title"] = "Train Passenger:",
            ["gui_settings_tab_transportType_trainPassenger_description"] = "Train Passenger",
            ["gui_settings_tab_transportType_waterPassenger_title"] = "Water Passenger:",
            ["gui_settings_tab_transportType_waterPassenger_description"] = "Water Passenger",
            ["gui_settings_tab_transportType_airPassenger_title"] = "Air Passenger:",
            ["gui_settings_tab_transportType_airPassenger_description"] = "Air Passenger",
            ["gui_settings_tab_transportType_roadCargo_title"] = "Road Cargo:",
            ["gui_settings_tab_transportType_roadCargo_description"] = "Road Cargo",
            ["gui_settings_tab_transportType_trainCargo_title"] = "Train Cargo:",
            ["gui_settings_tab_transportType_trainCargo_description"] = "Train Cargo",
            ["gui_settings_tab_transportType_waterCargo_title"] = "Water Cargo:",
            ["gui_settings_tab_transportType_waterCargo_description"] = "Water Cargo",
            ["gui_settings_tab_transportType_airCargo_title"] = "Air Cargo:",
            ["gui_settings_tab_transportType_airCargo_description"] = "Air Cargo",
            ["gui_settings_tab_transportType_unknown_title"] = "Unknown:",
            ["gui_settings_tab_transportType_unknown_description"] = "Unknown",
            -- Line Type Tab
            ["gui_settings_tab_lineType"] = "Line Types",
            ["gui_settings_tab_lineType_local_title"] = "Local Line:",
            ["gui_settings_tab_lineType_local_description"] = "Local Line",
            ["gui_settings_tab_lineType_local_tooltip"] = "Lines that are within a town",
            ["gui_settings_tab_lineType_intercity_title"] = "Intercity Line:",
            ["gui_settings_tab_lineType_intercity_description"] = "Intercity Line",
            ["gui_settings_tab_lineType_intercity_tooltip"] = "Lines that connect two towns",
            ["gui_settings_tab_lineType_regional_title"] = "Regional Line:",
            ["gui_settings_tab_lineType_regional_description"] = "Regional Line",
            ["gui_settings_tab_lineType_regional_tooltip"] = "Lines that connect multiple towns",
            -- Cargo Type Tab
            ["gui_settings_tab_cargoType"] = "Cargo Types",
            ["gui_settings_tab_cargoType_separator_title"] = "Separator:",
            ["gui_settings_tab_cargoType_separator_description"] = "Cargo Type Separator",
            ["gui_settings_tab_cargoType_separator_tooltip"] = "Separator between the cargo types. ex. 'Goods - Food'",
            ["gui_settings_tab_cargoType_showType_title"] = "Cargo Name Format:",
            ["gui_settings_tab_cargoType_showType_item_full"] = "Full Name",
            ["gui_settings_tab_cargoType_showType_item_short"] = "Short (3-letter)",
            -- Town Name Tab
            ["gui_settings_tab_townName"] = "Town Names",
            ["gui_settings_tab_townName_separator_title"] = "Separator:",
            ["gui_settings_tab_townName_separator_description"] = "Town Name Separator",
            ["gui_settings_tab_townName_separator_tooltip"] = "Separator between the town names. ex. 'City1 - City2'",
            ["gui_settings_tab_townName_showType_title"] = "Town Name Format:",
            ["gui_settings_tab_townName_showType_item_full"] = "Full Name",
            ["gui_settings_tab_townName_showType_item_short"] = "Short (3-letter)",
            -- Debug Tab
            ["gui_settings_tab_debug"] = "Debug",
            ["gui_settings_tab_debug_logLevel_title"] = "Log Level:",
            ["gui_settings_tab_debug_reset_title"] = "Reset Settings",
            ["gui_settings_preview_title"] = "Preview",
            ["gui_settings_preview_tooltip"] = "A live preview of how the current convention will render",
            ["gui_settings_preview_updates_tooltip"] =
            "Preview updates live as you change the convention or related settings",
        },
        de = {
            ["mod_description"] = "Benennt neue Linien automatisch basierend auf anpassbaren Benennungskonventionen",

            -- Einstellungen Fenster
            ["gui_settings_title"] = "Auto Linienbenennung Einstellungen",
            ["gui_settings_tooltip"] = "Auto Linienbenennung Einstellungen öffnen",
            -- Allgemein Tab
            ["gui_settings_tab_general"] = "Allgemein",
            ["gui_settings_tab_general_enabling_title"] = "Aktivieren:",
            ["gui_settings_tab_general_enabling_description"] = "Mod aktivieren oder deaktivieren",
            ["gui_settings_tab_general_enabling_tooltip"] = "Mod aktivieren oder deaktivieren",
            ["gui_settings_tab_general_prefix_title"] = "Präfix deaktivieren:",
            ["gui_settings_tab_general_prefix_description"] = "Präfix deaktivieren",
            ["gui_settings_tab_general_prefix_tooltip"] = "Linien mit diesem Präfix werden nicht umbenannt",
            ["gui_settings_tab_general_convention_title"] = "Aktive Konvention:",
            ["gui_settings_tab_general_convention_description"] = "Aktive Konvention",
            ["gui_settings_tab_general_convention_tooltip"] = "Die aktive Benennungskonvention auswählen",
            ["gui_settings_tab_general_autoUpdate_title"] = "Auto-Aktualisierung:",
            ["gui_settings_tab_general_autoUpdate_description"] = "Auto-Aktualisierung",
            ["gui_settings_tab_general_autoUpdate_tooltip"] = "Liniennamen automatisch aktualisieren",
            ["gui_settings_tab_general_autoUpdateInterval_title"] = "Intervall für Auto-Aktualisierung",
            ["gui_settings_tab_general_autoUpdateInterval_description"] = "Minuten",
            ["gui_settings_tab_general_autoUpdateInterval_tooltip"] = "Intervall für die Auto-Aktualisierung festlegen",
            -- Transporttypen Tab
            ["gui_settings_tab_transportType"] = "Transporttypen",
            ["gui_settings_tab_transportType_roadPassenger_title"] = "Straßenpassagiere:",
            ["gui_settings_tab_transportType_roadPassenger_description"] = "Straßenpassagiere",
            ["gui_settings_tab_transportType_tramPassenger_title"] = "Straßenbahnpassagiere:",
            ["gui_settings_tab_transportType_tramPassenger_description"] = "Straßenbahnpassagiere",
            ["gui_settings_tab_transportType_trainPassenger_title"] = "Zugpassagiere:",
            ["gui_settings_tab_transportType_trainPassenger_description"] = "Zugpassagiere",
            ["gui_settings_tab_transportType_waterPassenger_title"] = "Wasserpassagiere:",
            ["gui_settings_tab_transportType_waterPassenger_description"] = "Wasserpassagiere",
            ["gui_settings_tab_transportType_airPassenger_title"] = "Flugpassagiere:",
            ["gui_settings_tab_transportType_airPassenger_description"] = "Flugpassagiere",
            ["gui_settings_tab_transportType_roadCargo_title"] = "Straßengüter:",
            ["gui_settings_tab_transportType_roadCargo_description"] = "Straßengüter",
            ["gui_settings_tab_transportType_trainCargo_title"] = "Zuggüter:",
            ["gui_settings_tab_transportType_trainCargo_description"] = "Zuggüter",
            ["gui_settings_tab_transportType_waterCargo_title"] = "Wassergüter:",
            ["gui_settings_tab_transportType_waterCargo_description"] = "Wassergüter",
            ["gui_settings_tab_transportType_airCargo_title"] = "Fluggüter:",
            ["gui_settings_tab_transportType_airCargo_description"] = "Fluggüter",
            ["gui_settings_tab_transportType_unknown_title"] = "Unbekannt:",
            ["gui_settings_tab_transportType_unknown_description"] = "Unbekannt",
            -- Linientypen Tab
            ["gui_settings_tab_lineType"] = "Linientypen",
            ["gui_settings_tab_lineType_local_title"] = "Lokale Linie:",
            ["gui_settings_tab_lineType_local_description"] = "Lokale Linie",
            ["gui_settings_tab_lineType_local_tooltip"] = "Linien innerhalb einer Stadt",
            ["gui_settings_tab_lineType_intercity_title"] = "Intercity-Linie:",
            ["gui_settings_tab_lineType_intercity_description"] = "Intercity-Linie",
            ["gui_settings_tab_lineType_intercity_tooltip"] = "Linien, die zwei Städte verbinden",
            ["gui_settings_tab_lineType_regional_title"] = "Regionale Linie:",
            ["gui_settings_tab_lineType_regional_description"] = "Regionale Linie",
            ["gui_settings_tab_lineType_regional_tooltip"] = "Linien, die mehrere Städte verbinden",
            -- Gütertypen Tab
            ["gui_settings_tab_cargoType"] = "Gütertypen",
            ["gui_settings_tab_cargoType_separator_title"] = "Trennzeichen:",
            ["gui_settings_tab_cargoType_separator_description"] = "Trennzeichen für Gütertypen",
            ["gui_settings_tab_cargoType_separator_tooltip"] =
            "Trennzeichen zwischen den Gütertypen. z.B. 'Waren - Lebensmittel'",
            ["gui_settings_tab_cargoType_showType_title"] = "Format für Güternamen:",
            ["gui_settings_tab_cargoType_showType_item_full"] = "Vollständiger Name",
            ["gui_settings_tab_cargoType_showType_item_short"] = "Kurz (3 Buchstaben)",
            -- Stadtnamen Tab
            ["gui_settings_tab_townName"] = "Stadtnamen",
            ["gui_settings_tab_townName_separator_title"] = "Trennzeichen:",
            ["gui_settings_tab_townName_separator_description"] = "Trennzeichen für Stadtnamen",
            ["gui_settings_tab_townName_separator_tooltip"] =
            "Trennzeichen zwischen den Städtenamen. z.B. 'Stadt1 - Stadt2'",
            ["gui_settings_tab_townName_showType_title"] = "Format für Stadtnamen:",
            ["gui_settings_tab_townName_showType_item_full"] = "Vollständiger Name",
            ["gui_settings_tab_townName_showType_item_short"] = "Kurz (3 Buchstaben)",
            -- Debug Tab
            ["gui_settings_tab_debug"] = "Debug",
            ["gui_settings_tab_debug_logLevel_title"] = "Log-Level:",
            ["gui_settings_tab_debug_reset_title"] = "Einstellungen zurücksetzen",
            ["gui_settings_preview_title"] = "Vorschau",
            ["gui_settings_preview_tooltip"] = "Eine Live-Vorschau, wie die aktuelle Konvention gerendert wird",
            ["gui_settings_preview_updates_tooltip"] =
            "Die Vorschau wird live aktualisiert, wenn Sie die Konvention oder verwandte Einstellungen ändern",
        },
        ru = {
            ["mod_description"] = "Автоматически называет новые линии на основе настраиваемых шаблонов",

            -- Окно Настроек
            ["gui_settings_title"] = "Настройки Автоматического Названия Линий",
            ["gui_settings_tooltip"] = "Открыть настройки автоматического названия линий",
            -- Общий Вкладка
            ["gui_settings_tab_general"] = "Общие",
            ["gui_settings_tab_general_enabling_title"] = "Включение:",
            ["gui_settings_tab_general_enabling_description"] = "Включить или отключить мод",
            ["gui_settings_tab_general_enabling_tooltip"] = "Включить или отключить мод",
            ["gui_settings_tab_general_prefix_title"] = "Отключить Префикс:",
            ["gui_settings_tab_general_prefix_description"] = "Отключить префикс",
            ["gui_settings_tab_general_prefix_tooltip"] = "Линии с этим префиксом не будут переименованы",
            ["gui_settings_tab_general_convention_title"] = "Активный Шаблон:",
            ["gui_settings_tab_general_convention_description"] = "Активный шаблон",
            ["gui_settings_tab_general_convention_tooltip"] = "Выберите активный шаблон названия",
            ["gui_settings_tab_general_autoUpdate_title"] = "Автообновление:",
            ["gui_settings_tab_general_autoUpdate_description"] = "Автообновление",
            ["gui_settings_tab_general_autoUpdate_tooltip"] = "Автоматически обновлять названия линий",
            ["gui_settings_tab_general_autoUpdateInterval_title"] = "Интервал Автообновления",
            ["gui_settings_tab_general_autoUpdateInterval_description"] = "минуты",
            ["gui_settings_tab_general_autoUpdateInterval_tooltip"] = "Установить интервал для автообновления",
            -- Вкладка Типы Транспорта
            ["gui_settings_tab_transportType"] = "Типы Транспорта",
            ["gui_settings_tab_transportType_roadPassenger_title"] = "Автопассажиры:",
            ["gui_settings_tab_transportType_roadPassenger_description"] = "Автопассажиры",
            ["gui_settings_tab_transportType_tramPassenger_title"] = "Трамвайные пассажиры:",
            ["gui_settings_tab_transportType_tramPassenger_description"] = "Трамвайные пассажиры",
            ["gui_settings_tab_transportType_trainPassenger_title"] = "Железнодорожные пассажиры:",
            ["gui_settings_tab_transportType_trainPassenger_description"] = "Железнодорожные пассажиры",
            ["gui_settings_tab_transportType_waterPassenger_title"] = "Водные пассажиры:",
            ["gui_settings_tab_transportType_waterPassenger_description"] = "Водные пассажиры",
            ["gui_settings_tab_transportType_airPassenger_title"] = "Авиа пассажиры:",
            ["gui_settings_tab_transportType_airPassenger_description"] = "Авиа пассажиры",
            ["gui_settings_tab_transportType_roadCargo_title"] = "Автогрузы:",
            ["gui_settings_tab_transportType_roadCargo_description"] = "Автогрузы",
            ["gui_settings_tab_transportType_trainCargo_title"] = "Железнодорожные грузы:",
            ["gui_settings_tab_transportType_trainCargo_description"] = "Железнодорожные грузы",
            ["gui_settings_tab_transportType_waterCargo_title"] = "Водные грузы:",
            ["gui_settings_tab_transportType_waterCargo_description"] = "Водные грузы",
            ["gui_settings_tab_transportType_airCargo_title"] = "Авиа грузы:",
            ["gui_settings_tab_transportType_airCargo_description"] = "Авиа грузы",
            ["gui_settings_tab_transportType_unknown_title"] = "Неизвестно:",
            ["gui_settings_tab_transportType_unknown_description"] = "Неизвестно",
            -- Вкладка Типы Линий
            ["gui_settings_tab_lineType"] = "Типы Линий",
            ["gui_settings_tab_lineType_local_title"] = "Местная Линия:",
            ["gui_settings_tab_lineType_local_description"] = "Местная линия",
            ["gui_settings_tab_lineType_local_tooltip"] = "Линии в пределах одного города",
            ["gui_settings_tab_lineType_intercity_title"] = "Междугородняя Линия:",
            ["gui_settings_tab_lineType_intercity_description"] = "Междугородняя линия",
            ["gui_settings_tab_lineType_intercity_tooltip"] = "Линии, соединяющие два города",
            ["gui_settings_tab_lineType_regional_title"] = "Региональная Линия:",
            ["gui_settings_tab_lineType_regional_description"] = "Региональная линия",
            ["gui_settings_tab_lineType_regional_tooltip"] = "Линии, соединяющие несколько городов",
            -- Вкладка Типы Грузов
            ["gui_settings_tab_cargoType"] = "Типы Грузов",
            ["gui_settings_tab_cargoType_separator_title"] = "Разделитель:",
            ["gui_settings_tab_cargoType_separator_description"] = "Разделитель для типов грузов",
            ["gui_settings_tab_cargoType_separator_tooltip"] = "Разделитель между типами грузов, напр. 'Товары - Еда'",
            ["gui_settings_tab_cargoType_showType_title"] = "Формат Названия Груза:",
            ["gui_settings_tab_cargoType_showType_item_full"] = "Полное название",
            ["gui_settings_tab_cargoType_showType_item_short"] = "Короткое (3 буквы)",
            -- Вкладка Названия Городов
            ["gui_settings_tab_townName"] = "Названия Городов",
            ["gui_settings_tab_townName_separator_title"] = "Разделитель:",
            ["gui_settings_tab_townName_separator_description"] = "Разделитель для названий городов",
            ["gui_settings_tab_townName_separator_tooltip"] =
            "Разделитель между названиями городов, напр. 'Город1 - Город2'",
            ["gui_settings_tab_townName_showType_title"] = "Формат Названия Города:",
            ["gui_settings_tab_townName_showType_item_full"] = "Полное название",
            ["gui_settings_tab_townName_showType_item_short"] = "Короткое (3 буквы)",
            -- Вкладка Отладка
            ["gui_settings_tab_debug"] = "Отладка",
            ["gui_settings_tab_debug_logLevel_title"] = "Уровень Логов:",
            ["gui_settings_tab_debug_reset_title"] = "Сбросить Настройки",
            ["gui_settings_preview_title"] = "Предпросмотр",
            ["gui_settings_preview_tooltip"] = "Живой пример отображения текущего шаблона",
            ["gui_settings_preview_updates_tooltip"] =
            "Предпросмотр обновляется в реальном времени при изменении шаблона или сопутствующих настроек",
        },
        tr = {
            ["mod_description"] =
            "Özelleştirilebilir isimlendirme kurallarına göre yeni hatları otomatik olarak adlandırır",

            -- Ayarlar Penceresi
            ["gui_settings_title"] = "Otomatik Hat İsimlendirici Ayarları",
            ["gui_settings_tooltip"] = "Otomatik Hat İsimlendirici Ayarlarını Aç",
            -- Genel Sekme
            ["gui_settings_tab_general"] = "Genel",
            ["gui_settings_tab_general_enabling_title"] = "Etkinleştirme:",
            ["gui_settings_tab_general_enabling_description"] = "Modu etkinleştir veya devre dışı bırak",
            ["gui_settings_tab_general_enabling_tooltip"] = "Modu etkinleştir veya devre dışı bırak",
            ["gui_settings_tab_general_prefix_title"] = "Öneki Devre Dışı Bırak:",
            ["gui_settings_tab_general_prefix_description"] = "Öneki devre dışı bırak",
            ["gui_settings_tab_general_prefix_tooltip"] = "Bu öneke sahip hatlar yeniden adlandırılmayacak",
            ["gui_settings_tab_general_convention_title"] = "Aktif Şablon:",
            ["gui_settings_tab_general_convention_description"] = "Aktif şablon",
            ["gui_settings_tab_general_convention_tooltip"] = "Aktif isimlendirme şablonunu seçin",
            ["gui_settings_tab_general_autoUpdate_title"] = "Otomatik Güncelleme:",
            ["gui_settings_tab_general_autoUpdate_description"] = "Otomatik Güncelleme",
            ["gui_settings_tab_general_autoUpdate_tooltip"] = "Hat isimlerini otomatik olarak güncelle",
            ["gui_settings_tab_general_autoUpdateInterval_title"] = "Otomatik Güncelleme Aralığı",
            ["gui_settings_tab_general_autoUpdateInterval_description"] = "dakika",
            ["gui_settings_tab_general_autoUpdateInterval_tooltip"] = "Otomatik güncelleme için aralığı ayarla",
            -- Taşıma Türleri Sekmesi
            ["gui_settings_tab_transportType"] = "Taşıma Türleri",
            ["gui_settings_tab_transportType_roadPassenger_title"] = "Karayolu Yolcu:",
            ["gui_settings_tab_transportType_roadPassenger_description"] = "Karayolu Yolcu",
            ["gui_settings_tab_transportType_tramPassenger_title"] = "Tramvay Yolcu:",
            ["gui_settings_tab_transportType_tramPassenger_description"] = "Tramvay Yolcu",
            ["gui_settings_tab_transportType_trainPassenger_title"] = "Tren Yolcu:",
            ["gui_settings_tab_transportType_trainPassenger_description"] = "Tren Yolcu",
            ["gui_settings_tab_transportType_waterPassenger_title"] = "Su Yolcu:",
            ["gui_settings_tab_transportType_waterPassenger_description"] = "Su Yolcu",
            ["gui_settings_tab_transportType_airPassenger_title"] = "Hava Yolcu:",
            ["gui_settings_tab_transportType_airPassenger_description"] = "Hava Yolcu",
            ["gui_settings_tab_transportType_roadCargo_title"] = "Karayolu Yük:",
            ["gui_settings_tab_transportType_roadCargo_description"] = "Karayolu Yük",
            ["gui_settings_tab_transportType_trainCargo_title"] = "Tren Yük:",
            ["gui_settings_tab_transportType_trainCargo_description"] = "Tren Yük",
            ["gui_settings_tab_transportType_waterCargo_title"] = "Su Yük:",
            ["gui_settings_tab_transportType_waterCargo_description"] = "Su Yük",
            ["gui_settings_tab_transportType_airCargo_title"] = "Hava Yük:",
            ["gui_settings_tab_transportType_airCargo_description"] = "Hava Yük",
            ["gui_settings_tab_transportType_unknown_title"] = "Bilinmeyen:",
            ["gui_settings_tab_transportType_unknown_description"] = "Bilinmeyen",
            -- Hat Türleri Sekmesi
            ["gui_settings_tab_lineType"] = "Hat Türleri",
            ["gui_settings_tab_lineType_local_title"] = "Yerel Hat:",
            ["gui_settings_tab_lineType_local_description"] = "Yerel Hat",
            ["gui_settings_tab_lineType_local_tooltip"] = "Bir şehir içindeki hatlar",
            ["gui_settings_tab_lineType_intercity_title"] = "Şehirlerarası Hat:",
            ["gui_settings_tab_lineType_intercity_description"] = "Şehirlerarası Hat",
            ["gui_settings_tab_lineType_intercity_tooltip"] = "İki şehri birbirine bağlayan hatlar",
            ["gui_settings_tab_lineType_regional_title"] = "Bölgesel Hat:",
            ["gui_settings_tab_lineType_regional_description"] = "Bölgesel Hat",
            ["gui_settings_tab_lineType_regional_tooltip"] = "Birden fazla şehri birbirine bağlayan hatlar",
            -- Yük Türleri Sekmesi
            ["gui_settings_tab_cargoType"] = "Yük Türleri",
            ["gui_settings_tab_cargoType_separator_title"] = "Ayraç:",
            ["gui_settings_tab_cargoType_separator_description"] = "Yük Türü Ayıracı",
            ["gui_settings_tab_cargoType_separator_tooltip"] = "Yük türleri arasındaki ayraç. Örn: 'Eşyalar - Yemek'",
            ["gui_settings_tab_cargoType_showType_title"] = "Yük İsmi Formatı:",
            ["gui_settings_tab_cargoType_showType_item_full"] = "Tam İsim",
            ["gui_settings_tab_cargoType_showType_item_short"] = "Kısa (3 harf)",
            -- Şehir Adları Sekmesi
            ["gui_settings_tab_townName"] = "Şehir Adları",
            ["gui_settings_tab_townName_separator_title"] = "Ayraç:",
            ["gui_settings_tab_townName_separator_description"] = "Şehir Adı Ayıracı",
            ["gui_settings_tab_townName_separator_tooltip"] = "Şehir adları arasındaki ayraç. Örn: 'Şehir1 - Şehir2'",
            ["gui_settings_tab_townName_showType_title"] = "Şehir Adı Formatı:",
            ["gui_settings_tab_townName_showType_item_full"] = "Tam İsim",
            ["gui_settings_tab_townName_showType_item_short"] = "Kısa (3 harf)",
            -- Hata Ayıklama Sekmesi
            ["gui_settings_tab_debug"] = "Hata Ayıklama",
            ["gui_settings_tab_debug_logLevel_title"] = "Log Seviyesi:",
            ["gui_settings_tab_debug_reset_title"] = "Ayarları Sıfırla",
            ["gui_settings_preview_title"] = "Önizleme",
            ["gui_settings_preview_tooltip"] = "Mevcut şablonun nasıl görüneceğinin canlı önizlemesi",
            ["gui_settings_preview_updates_tooltip"] =
            "Önizleme, şablonu veya ilgili ayarları değiştirirken canlı olarak güncellenir",
        }

    }
end
